<?php

use App\Tag;
use Illuminate\Database\Seeder;

class TagsTableSeeder extends Seeder
{
    public function run()
    {
        $this->addFeaturedTags();
        $this->addOtherTags();
        $this->markPopularTags();
    }

    // these are for the tag streams that get shown on the homepage / feed's right rail
    private function addFeaturedTags()
    {
        $currentTimestamp = date("Y-m-d H:i:s");
        $featuredTags = [
            [
                "name"              => "Help",
                "slug"              => "help",
                "active"            => 1,
                "is_featured"       => 1,
                "featured_order"    => 1,
                "tag_bg_color"      => "#4fa93a",
                "tag_fg_color"      => "#ffffff",
                "cta_title"         => "Ask for Help",
                "cta_subtitle"      => "Let's figure this out together.",
                "created_at"        => $currentTimestamp,
                "updated_at"        => $currentTimestamp,
                "deleted_at"        => null,
            ],
            [
                "name"              => "AMA",
                "slug"              => "ama",
                "active"            => 1,
                "is_featured"       => 1,
                "featured_order"    => 2,
                "tag_bg_color"      => "#4594ba",
                "tag_fg_color"      => "#ffffff",
                "cta_title"         => "Start an \"AMA\"",
                "cta_subtitle"      => "Everybody has a story to tell.",
                "created_at"        => $currentTimestamp,
                "updated_at"        => $currentTimestamp,
                "deleted_at"        => null,
            ],
            [
                "name"              => "Challenge",
                "slug"              => "challenge",
                "active"            => 1,
                "is_featured"       => 1,
                "featured_order"    => 3,
                "tag_bg_color"      => "#f1760e",
                "tag_fg_color"      => "#ffffff",
                "cta_title"         => "Create a Challenge",
                "cta_subtitle"      => "Flex your skills, stay sharp.",
                "created_at"        => $currentTimestamp,
                "updated_at"        => $currentTimestamp,
                "deleted_at"        => null,
            ],
            [
                "name"              => "Discuss",
                "slug"              => "discuss",
                "active"            => 1,
                "is_featured"       => 1,
                "featured_order"    => 4,
                "tag_bg_color"      => "#2192de",
                "tag_fg_color"      => "#ffffff",
                "cta_title"         => "Start a Discussion",
                "cta_subtitle"      => "What does the community think?",
                "created_at"        => $currentTimestamp,
                "updated_at"        => $currentTimestamp,
                "deleted_at"        => null,
            ],
            [
                "name"              => "Explain Like I'm Five",
                "slug"              => "explainlikeimfive",
                "active"            => 1,
                "is_featured"       => 1,
                "featured_order"    => 5,
                "tag_bg_color"      => "#7beda5",
                "tag_fg_color"      => "#000000",
                "cta_title"         => "Ask for an Explanation",
                "cta_subtitle"      => "Need simplicity in your life?",
                "created_at"        => $currentTimestamp,
                "updated_at"        => $currentTimestamp,
                "deleted_at"        => null,
            ],
            [
                "name"              => "Healthy Debate",
                "slug"              => "healthydebate",
                "active"            => 1,
                "is_featured"       => 1,
                "featured_order"    => 6,
                "tag_bg_color"      => "#f46c4d",
                "tag_fg_color"      => "#ffffff",
                "cta_title"         => "Start a Debate",
                "cta_subtitle"      => "We can't agree on everything.",
                "created_at"        => $currentTimestamp,
                "updated_at"        => $currentTimestamp,
                "deleted_at"        => null,
            ],
            [
                "name"              => "Meta",
                "slug"              => "meta",
                "active"            => 1,
                "is_featured"       => 1,
                "featured_order"    => 7,
                "tag_bg_color"      => "#fb5d04",
                "tag_fg_color"      => "#ffffff",
                "cta_title"         => "Start a Meta Discussion",
                "cta_subtitle"      => "About KeenBrain itself.",
                "created_at"        => $currentTimestamp,
                "updated_at"        => $currentTimestamp,
                "deleted_at"        => null,
            ],
            [
                "name"              => "Watercooler",
                "slug"              => "watercooler",
                "active"            => 1,
                "is_featured"       => 1,
                "featured_order"    => 8,
                "tag_bg_color"      => "#7cb946",
                "tag_fg_color"      => "#ffffff",
                "cta_title"         => "Go Off-Topic",
                "cta_subtitle"      => "Light and off-topic chitchat.",
                "created_at"        => $currentTimestamp,
                "updated_at"        => $currentTimestamp,
                "deleted_at"        => null,
            ],
        ];

        Tag::insert($featuredTags);
    }

    private function addOtherTags()
    {
        $currentTimestamp = date("Y-m-d H:i:s");
        $otherTags = [
            [
                "name"          => "Leadership",
                "slug"          => "leadership",
                "active"        => 1,
                "is_featured"   => 0,
                "tag_bg_color"  => "#ee5611",
                "tag_fg_color"  => "#ffffff",
                "created_at"    => $currentTimestamp,
                "updated_at"    => $currentTimestamp,
                "deleted_at"    => null,
            ],
            [
                "name"          => "Tutorial",
                "slug"          => "tutorial",
                "active"        => 1,
                "is_featured"   => 0,
                "tag_bg_color"  => "#f3f085",
                "tag_fg_color"  => "#000000",
                "created_at"    => $currentTimestamp,
                "updated_at"    => $currentTimestamp,
                "deleted_at"    => null,
            ],
            [
                "name"          => "Productivity",
                "slug"          => "productivity",
                "active"        => 1,
                "is_featured"   => 0,
                "tag_bg_color"  => "#2a60d5",
                "tag_fg_color"  => "#ffffff",
                "created_at"    => $currentTimestamp,
                "updated_at"    => $currentTimestamp,
                "deleted_at"    => null,
            ],
            [
                "name"          => "Beginners",
                "slug"          => "beginners",
                "active"        => 1,
                "is_featured"   => 0,
                "tag_bg_color"  => "#4a9633",
                "tag_fg_color"  => "#ffffff",
                "created_at"    => $currentTimestamp,
                "updated_at"    => $currentTimestamp,
                "deleted_at"    => null,
            ],
            [
                "name"          => "Interviews",
                "slug"          => "interviews",
                "active"        => 1,
                "is_featured"   => 0,
                "tag_bg_color"  => "#8334af",
                "tag_fg_color"  => "#ffffff",
                "created_at"    => $currentTimestamp,
                "updated_at"    => $currentTimestamp,
                "deleted_at"    => null,
            ],
            [
                "name"          => "Career",
                "slug"          => "career",
                "active"        => 1,
                "is_featured"   => 0,
                "tag_bg_color"  => "#435b33",
                "tag_fg_color"  => "#ffffff",
                "created_at"    => $currentTimestamp,
                "updated_at"    => $currentTimestamp,
                "deleted_at"    => null,
            ],
            [
                "name"          => "Show Keenbrain",
                "slug"          => "showkeenbrain",
                "active"        => 1,
                "is_featured"   => 0,
                "tag_bg_color"  => "#ff1a00",
                "tag_fg_color"  => "#ffffff",
                "created_at"    => $currentTimestamp,
                "updated_at"    => $currentTimestamp,
                "deleted_at"    => null,
            ],
            [
                "name"          => "Motivation",
                "slug"          => "motivation",
                "active"        => 1,
                "is_featured"   => 0,
                "tag_bg_color"  => "#cfdfe9",
                "tag_fg_color"  => "#000000",
                "created_at"    => $currentTimestamp,
                "updated_at"    => $currentTimestamp,
                "deleted_at"    => null,
            ],
            [
                "name"          => "News",
                "slug"          => "news",
                "active"        => 1,
                "is_featured"   => 0,
                "tag_bg_color"  => "#aaffab",
                "tag_fg_color"  => "#000000",
                "created_at"    => $currentTimestamp,
                "updated_at"    => $currentTimestamp,
                "deleted_at"    => null,
            ],
            [
                "name"          => "Startup",
                "slug"          => "startup",
                "active"        => 1,
                "is_featured"   => 0,
                "tag_bg_color"  => "#13ecc2",
                "tag_fg_color"  => "#000000",
                "created_at"    => $currentTimestamp,
                "updated_at"    => $currentTimestamp,
                "deleted_at"    => null,
            ],
            [
                "name"          => "User Experience",
                "slug"          => "ux",
                "active"        => 1,
                "is_featured"   => 0,
                "tag_bg_color"  => "#e18b1e",
                "tag_fg_color"  => "#ffffff",
                "created_at"    => $currentTimestamp,
                "updated_at"    => $currentTimestamp,
                "deleted_at"    => null,
            ],
            [
                "name"          => "Weekly Retro",
                "slug"          => "weeklyretro",
                "active"        => 1,
                "is_featured"   => 0,
                "tag_bg_color"  => "#f00f70",
                "tag_fg_color"  => "#ffffff",
                "created_at"    => $currentTimestamp,
                "updated_at"    => $currentTimestamp,
                "deleted_at"    => null,
            ],
            [
                "name"          => "Psychology",
                "slug"          => "psychology",
                "active"        => 1,
                "is_featured"   => 0,
                "tag_bg_color"  => "#000000",
                "tag_fg_color"  => "#ffffff",
                "created_at"    => $currentTimestamp,
                "updated_at"    => $currentTimestamp,
                "deleted_at"    => null,
            ],
            [
                "name"          => "Today I Learned",
                "slug"          => "todayilearned",
                "active"        => 1,
                "is_featured"   => 0,
                "tag_bg_color"  => "#4db292",
                "tag_fg_color"  => "#ffffff",
                "created_at"    => $currentTimestamp,
                "updated_at"    => $currentTimestamp,
                "deleted_at"    => null,
            ],
            [
                "name"          => "Writing",
                "slug"          => "writing",
                "active"        => 1,
                "is_featured"   => 0,
                "tag_bg_color"  => "#6e6f91",
                "tag_fg_color"  => "#ffffff",
                "created_at"    => $currentTimestamp,
                "updated_at"    => $currentTimestamp,
                "deleted_at"    => null,
            ],
            [
                "name"          => "Graveyard",
                "slug"          => "graveyard",
                "active"        => 1,
                "is_featured"   => 0,
                "tag_bg_color"  => "#4e4e50",
                "tag_fg_color"  => "#ffffff",
                "created_at"    => $currentTimestamp,
                "updated_at"    => $currentTimestamp,
                "deleted_at"    => null,
            ],
            [
                "name"          => "Books",
                "slug"          => "books",
                "active"        => 1,
                "is_featured"   => 0,
                "tag_bg_color"  => "#9cefa6",
                "tag_fg_color"  => "#000000",
                "created_at"    => $currentTimestamp,
                "updated_at"    => $currentTimestamp,
                "deleted_at"    => null,
            ],
            [
                "name"          => "Contributors Wanted",
                "slug"          => "contributorswanted",
                "active"        => 1,
                "is_featured"   => 0,
                "tag_bg_color"  => "#495db6",
                "tag_fg_color"  => "#ffffff",
                "created_at"    => $currentTimestamp,
                "updated_at"    => $currentTimestamp,
                "deleted_at"    => null,
            ],
            [
                "name"          => "Personal News",
                "slug"          => "personalnews",
                "active"        => 1,
                "is_featured"   => 0,
                "tag_bg_color"  => "#5fa090",
                "tag_fg_color"  => "#ffffff",
                "created_at"    => $currentTimestamp,
                "updated_at"    => $currentTimestamp,
                "deleted_at"    => null,
            ],
            [
                "name"          => "Jokes",
                "slug"          => "jokes",
                "active"        => 1,
                "is_featured"   => 0,
                "tag_bg_color"  => "#e9d616",
                "tag_fg_color"  => "#000000",
                "created_at"    => $currentTimestamp,
                "updated_at"    => $currentTimestamp,
                "deleted_at"    => null,
            ],
            [
                "name"          => "Inclusion",
                "slug"          => "inclusion",
                "active"        => 1,
                "is_featured"   => 0,
                "tag_bg_color"  => "#637e9c",
                "tag_fg_color"  => "#ffffff",
                "created_at"    => $currentTimestamp,
                "updated_at"    => $currentTimestamp,
                "deleted_at"    => null,
            ],
            [
                "name"          => "Mental Health",
                "slug"          => "mentalhealth",
                "active"        => 1,
                "is_featured"   => 0,
                "tag_bg_color"  => "#56a96a",
                "tag_fg_color"  => "#ffffff",
                "created_at"    => $currentTimestamp,
                "updated_at"    => $currentTimestamp,
                "deleted_at"    => null,
            ],
            [
                "name"          => "Best Of",
                "slug"          => "bestof",
                "active"        => 1,
                "is_featured"   => 0,
                "tag_bg_color"  => "#ed124b",
                "tag_fg_color"  => "#ffffff",
                "created_at"    => $currentTimestamp,
                "updated_at"    => $currentTimestamp,
                "deleted_at"    => null,
            ],
            [
                "name"          => "Podcast",
                "slug"          => "podcast",
                "active"        => 1,
                "is_featured"   => 0,
                "tag_bg_color"  => "#ef5310",
                "tag_fg_color"  => "#ffffff",
                "created_at"    => $currentTimestamp,
                "updated_at"    => $currentTimestamp,
                "deleted_at"    => null,
            ],
            [
                "name"          => "Follow Friday",
                "slug"          => "followfriday",
                "active"        => 1,
                "is_featured"   => 0,
                "tag_bg_color"  => "#fac1d0",
                "tag_fg_color"  => "#000000",
                "created_at"    => $currentTimestamp,
                "updated_at"    => $currentTimestamp,
                "deleted_at"    => null,
            ],
        ];

        Tag::insert($otherTags);
    }

    private function markPopularTags()
    {
        $tagSlugsArray = ['discuss', 'healthydebate', 'watercooler', 'meta', 'help', 'ama'];
        $popular_order = 1;
        foreach ($tagSlugsArray as $tagSlug) {
            $updateSuccessful = Tag::where('slug', $tagSlug)->update(
                [
                    'is_popular' => '1',
                    'popular_order' => $popular_order,
                ]
            );
            if ($updateSuccessful) {
                $popular_order++;
            }
        }
    }
}
